apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
data:
  #smtp_auth_password: {{ .Values.alertmanager.smtp.password | b64enc }}
  smtp_auth_password: {{ .Files.Get "/home/hii/smtp_auth_password.txt" | b64enc | quote }}