apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.service.port }}
      nodePort: {{ .Values.alertmanager.service.nodePort }}
