apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: '{{ .Values.alertmanager.smtp.host }}'
      smtp_from: '{{ .Values.alertmanager.smtp.from }}'
      smtp_auth_username: '{{ .Values.alertmanager.smtp.username }}'
      smtp_auth_password: '$(smtp_auth_password)'  
      smtp_require_tls: true

    route:
      receiver: 'email'

    receivers:
      - name: 'email'
        email_configs:
          - to: '{{ .Values.alertmanager.receiverEmail }}'
            send_resolved: true
