apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: {{ .Values.dbCredentials.host | b64enc }}
  DB_PORT: {{ .Values.dbCredentials.port | b64enc }}
  DB_USER: {{ .Values.dbCredentials.user | b64enc }}
  #DB_PASSWORD: {{ .Values.dbCredentials.password | b64enc }}
  DB_PASSWORD: {{ .Files.Get "/home/hii/db_password_file.txt" | b64enc | quote }}
  DB_NAME: {{ .Values.dbCredentials.name | b64enc }}
