apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrape_interval }}

    scrape_configs:
      - job_name: 'stock_monitor'
        metrics_path: '/api/metrics/'
        static_configs:
          - targets: {{ toYaml .Values.prometheus.config.targets | nindent 12 }}

      - job_name: 'node_exporter'
        static_configs:
          - targets: ['node-exporter-prometheus-node-exporter.default.svc.cluster.local:9100']



    rule_files:
      - 'alert.rules.yml'

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'localhost:9093'
  alert.rules.yml: |
    groups:
      - name: stock_alerts
        rules:
          - alert: StockPriceChange
            expr: |
              (stock_price{symbol="AAPL"} - stock_price{symbol="AAPL"} offset 1d) / stock_price{symbol="AAPL"} * 100
              > 2
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Stock price for {{`{{ $labels.symbol }}`}} has changed by more than 10%"
              description: "Stock price has changed by {{`{{ $value }}`}}% in the last 24 hours."
